server:
  port: 8080
#  servlet:
#   context-path: /lauzIM
# 定位模板的目录
#spring.mvc.view.prefix=classpath:/templates/
# 给返回的页面添加后缀名
#spring.mvc.view.suffix=.html
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      # 配置数据源类型
      type:
        com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zrar
      username: root
      password: adminroot
      # 初始化，最小，最大连接数
      initialSize: 3
      minidle: 3
      maxActive: 18
      # 获取数据库连接等待的超时时间
      maxWait: 60000